In [1]:
import numpy as np
import sys
import MeCab

 # Japanese tokenizetion
 
 mecab

In [2]:
m = MeCab.Tagger ("-Ochasen")
print(m.parse ("今日もしないとね"))

今日	キョウ	今日	名詞-副詞可能		
も	モ	も	助詞-係助詞		
し	シ	する	動詞-自立	サ変・スル	未然形
ない	ナイ	ない	助動詞	特殊・ナイ	基本形
と	ト	と	助詞-接続助詞		
ね	ネ	ね	助詞-終助詞		
EOS



In [3]:
pwd

'/home/yanhua/Documents/jupyter/yan/demo/RNN/Natural_Language_Processing'

In [4]:
from gensim.models import Word2Vec

In [5]:
sentences = [["cat", "say", "meow"], ["dog", "say", "woof"]]

In [6]:
model = Word2Vec(sentences, min_count=1)

In [7]:
say_vector = model['say']  # get vector for word

/home/yanhua/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


In [8]:
say_vector

array([ 1.4251153e-03, -1.6253097e-04, -2.6126101e-03, -6.3351108e-05,
       -2.2075193e-03,  3.4370341e-03,  4.2157872e-03,  4.4553829e-03,
        2.0769991e-03, -1.8314234e-03, -1.8645810e-03,  4.3295491e-03,
        4.1067647e-03, -4.7371993e-03, -1.3795249e-03,  1.4547110e-03,
        1.2371828e-03, -3.7863550e-03,  3.9816480e-03,  4.8498712e-03,
        1.0015409e-03, -2.9589006e-04, -1.5174053e-03,  3.9856574e-03,
       -1.6477914e-03,  1.7932791e-03, -1.8799044e-03,  2.1412845e-03,
       -4.5422353e-03, -1.3146297e-03, -8.8776962e-04,  3.3260663e-03,
       -4.7798897e-04,  1.9947863e-03, -1.5988876e-03,  2.1081152e-03,
       -6.8036932e-04, -7.5350440e-04, -2.2899872e-03, -8.5218344e-04,
        4.7037960e-03,  2.5203368e-03,  1.3808474e-03,  2.4380517e-04,
        3.8636234e-03,  1.5217823e-03, -3.4907355e-03, -4.6238690e-03,
        2.9734159e-03,  4.0107225e-03, -3.8078835e-03, -1.2959006e-03,
       -1.6437615e-03, -3.0163869e-03,  6.0245860e-04, -4.0520984e-03,
      

In [9]:
pwd

'/home/yanhua/Documents/jupyter/yan/demo/RNN/Natural_Language_Processing'

In [10]:
from gensim.models.word2vec import Word2Vec

In [11]:
model_path = 'data/word2vec/word2vec.gensim.model'
model = Word2Vec.load(model_path)

In [12]:
print(model)

Word2Vec(vocab=335476, size=50, alpha=0.025)


In [13]:
from collections import defaultdict
from sklearn.cluster import KMeans

In [14]:
max_vocab = 30000
vocab = list(model.wv.vocab.keys())[:max_vocab]
vectors = [model.wv[word] for word in vocab]

In [ ]:
n_clusters = 1000
kmeans_model = KMeans(n_clusters=n_clusters, verbose=1, random_state=42, n_jobs=-1)
kmeans_model.fit(vectors)

In [16]:
cluster_labels = kmeans_model.labels_
cluster_to_words = defaultdict(list)
for cluster_id, word in zip(cluster_labels, vocab):
    cluster_to_words[cluster_id].append(word)

In [ ]:
for words in cluster_to_words.values():
    print(words[:10])

['『', '羅針盤', '"（『', '(『', 'ラリック', '航海日誌', '若き彗星の肖像']

['GO', 'POWER', '&', 'STYLE', 'LEVEL', 'TO', 'THE', 'TOKYO', 'NO', 'YOUR']

['!', 'くん', '!〜', '〜', '?」（', 'サブちゃん', '熱血', '夕陽', '心温まる', '!!']

['ガリバー', 'お元気ですか', '小難しい', 'さみっと', '積木くずし', '由里', '積木', '福井裕佳梨', '突き詰める', 'きまぐれ']

['』', '著書', '著作', '自著', '旅行記', '主著', '二十世紀', 'ブラヴァツキー', '自伝', 'ノストラダムス']

['（', '(', 'または', '：', '』(', '；', '("', ';', '」(', '："']

['ゴーゴー', 'ふれあい', 'こんにちは', 'うたい文句', 'アニ', '日和', 'まるごと', 'みちのく', 'くつろぎ', 'お年玉']

['）', 'いっか', 'ざい', 'せいし', 'けいざい', 'えいきゅう', 'しすう', 'しんぶ', 'りかん', 'ほんこく']

['は', '、', 'で', '。', 'から', 'の', 'に', 'も', 'が', 'より']

['関西テレビ', '岡山放送', 'テレビ新広島', 'テレビ愛媛', 'BSフジ', 'スポンサードネット', 'テレビ西日本', 'FNS', 'フジテレビ', '東海テレビ']

In [ ]:
for words in cluster_to_words.values():
    print(words[:20])

['こと', 'だけ', 'か', 'ので', 'はず', 'まま', 'ほど', '状態', 'かも', 'ところ', '事', 'のに', '限り', 'くらい', '程', 'つもり', '代物', 'かぎり', '行き場', '筈']

['事実上', '名実', '実質的', '短期間', '形式上', '一応', '単独', '一時', '実質', '引き続き', '体制']

['JR西日本', '東海旅客鉄道', 'JR東海', '和歌山電鐵', '貴志川線', '国鉄', '軽便鉄道', '近鉄', '京阪宇治交通', '京阪宇治バス', '水浜', '日本道路公団', '東日本旅客鉄道', 'JR東日本', '日本貨物鉄道', 'JR貨物', '新京成電鉄', '東武鉄道', '鉄道事業法', '常磐新線']

['営業', '小売業者', '販売', 'メーカー', '商品', '各社', '仕入れ', '卸売', '小売', '広告', '業者', '従業員', 'ディーラー', '代理店', '取り扱い', '大手', '販売店', '中古車', '自前', '日本国内']

['圏内', '周回', '走り', '地点', '目標', '軌道', '走破', '時速', 'h', '距離', '高速', '一周', '極点', '短距離', '長距離', '最短', '中距離', '進路', '最速', '追い風']

['ロケ地', '跡地', '都内', 'マンション', '火葬場', '敷地内', 'アパート', '民宿', '空き家', 'ホテル', '事務所', 'ロケーション撮影', 'ロケハン', 'レストハウス', '原宿', 'スタジオ', 'ビル', '屋上', '千里丘', '倉庫']

['範囲', '概ね', '下位', '単位', '未満', 'ないし', 'ばらつき', 'おおむね', 'だいたい', '大体', 'おおよそ']

['北', '南', '北部', '沿い', '境', '南端', '境界', '南部', '西', '東', '南西', '北側', '対岸', '中心部', '境界線', '北西', '中部', '南北', '北東', '南側']

['北海道', '沖縄', '関東地方', '東海地方', '関東', '東海', '日本全国', '全国', '関西', '京阪神', '中京圏', '九州', '広域圏', '東北', '西日本', '近畿', '近畿地方', '管内', '両県', '甲信越地方']

['1回目', '2回', '8回', '1回', '12回', '7回', '3週', '4週', '6週', '11回', '5回', '10回', '9回', '4回', '6回', '1週目', '3回', '1週', '一報', 'NHK紅白歌合戦']

In [19]:
a=model.wv['関西']

In [24]:
b=model.wv['京阪神']

In [23]:
c=model.wv['書き換え']

In [22]:
a

array([ 0.06097883,  0.0548775 ,  0.04423802, -0.01335528,  0.2540089 ,
        0.04726651, -0.2625341 , -0.04817509,  0.06873596,  0.2538341 ,
        0.25970745, -0.06023698, -0.11471419,  0.20452783, -0.17527722,
       -0.05473799, -0.12370639, -0.11321306,  0.03210169, -0.08080786,
       -0.02490497, -0.11166706,  0.10667294,  0.03653087, -0.14704296,
       -0.03920539,  0.019731  ,  0.06971741,  0.05628693,  0.22078079,
       -0.18291001,  0.06192484,  0.10575615,  0.05539227, -0.03277026,
       -0.03865077,  0.06283504, -0.22125009,  0.11877664, -0.17072822,
       -0.21894012,  0.01533967, -0.0571952 , -0.17841175, -0.34246624,
        0.22239536,  0.01235264,  0.18045105,  0.01914061, -0.22141388],
      dtype=float32)

#### If a is movie id , b is user id, then dot product is the score of similarity. (user like or not this movie.)

this is high dimention calculation.

high dimention like neural signo. and calculat it for the results.



In [25]:
np.dot(a,b)

0.64192325

In [27]:
np.dot(a,a)

1.0

In [28]:
model.wv.similarity('関西','京阪神')

0.6419232925927187

In [29]:
model.wv.similarity('エンジニア','上')

-0.04456206076653568

In [30]:
model.wv.similarity('上','下')

0.5566014899029449

In [31]:
model.wv.similarity('に対して','に対する')

0.8029499599661047

In [32]:
model.wv.similar_by_word('関西')

[('関東', 0.7904562950134277),
 ('東海', 0.7850244045257568),
 ('名古屋', 0.7849997282028198),
 ('関西地方', 0.7842962741851807),
 ('福岡', 0.7842126488685608),
 ('西日本', 0.777925968170166),
 ('九州', 0.7719117403030396),
 ('札幌', 0.769116997718811),
 ('東日本', 0.7553790807723999),
 ('関西圏', 0.7469385862350464)]

In [33]:
model.wv['東日本']

array([ 1.9019004e-03,  7.6924093e-02,  4.5656921e-05,  3.8070325e-02,
        2.3742664e-01,  4.5793399e-02, -2.4152388e-01, -6.5767974e-02,
        3.3734277e-01,  2.1425964e-01,  1.5608071e-01,  8.8700235e-02,
       -2.0588864e-02,  1.2649038e-01, -8.8807475e-03, -6.3999161e-02,
       -1.7451532e-01, -7.8131676e-02,  4.3507103e-02,  2.3658967e-02,
        2.7790360e-02, -2.0005094e-01, -1.7779160e-02, -2.4918655e-02,
        5.7872001e-02,  9.6592885e-03, -1.2809505e-02,  2.6932463e-02,
       -9.6038930e-02,  5.6382347e-02, -5.3153928e-02,  1.0701250e-01,
        1.0073025e-01,  2.7167630e-01, -1.2989057e-02,  1.8048836e-02,
        1.7873101e-02, -2.0694500e-01, -8.1164293e-02, -2.0905440e-01,
       -3.1024978e-01, -1.3187174e-01, -2.1217562e-01, -2.1197464e-01,
       -2.9577792e-01,  1.8283753e-01, -1.0651054e-02,  5.8291797e-02,
        3.6730979e-02, -1.9988927e-01], dtype=float32)

# How much is the cosin distance. 
Equation : cos(A) = < b,c > / (|b| * |c|)

cos(A) =  product / norm * norm

norm 2. 
norm 1 norm(x,ord=1)

In [34]:
dist = np.linalg.norm(a-b)

In [35]:
dist

0.84625846

In [36]:
np.linalg.norm(model.wv['京阪神'])

0.99999994

In [37]:
np.linalg.norm(model.wv['東日本'])

0.99999994

In [38]:
from numpy import linalg as LA

In [39]:
e=[1,1]
LA.norm(e)

1.4142135623730951

# How much is the cosin distance. 
Equation : cos(A) = < b,c > / (|b| * |c|)

cos(A) =  product / norm * norm

norm 2. 
norm 1 norm(x,ord=1)

In [47]:
LA.norm(e,ord=1),LA.norm(e,ord=2),LA.norm(e,ord=1000),LA.norm(e,np.inf)

(2.0, 1.4142135623730951, 1.0006933874625807, 1.0)

In [45]:
LA.norm(e,ord=10000)

1.0000693171203765

In [46]:
LA.norm(e,np.inf)

1.0

In [48]:
LA.norm(e,ord=1)

2.0

In [49]:
LA.norm(b)

0.99999994

In [50]:
print(m.parse ("今日もしないとね"))

今日	キョウ	今日	名詞-副詞可能		
も	モ	も	助詞-係助詞		
し	シ	する	動詞-自立	サ変・スル	未然形
ない	ナイ	ない	助動詞	特殊・ナイ	基本形
と	ト	と	助詞-接続助詞		
ね	ネ	ね	助詞-終助詞		
EOS



In [51]:
model.wv['も']

array([ 0.0080338 ,  0.1830312 ,  0.13818194, -0.03569911,  0.09460398,
       -0.0277751 , -0.0573119 , -0.04554379, -0.19222827, -0.01455549,
       -0.03190554, -0.05722512, -0.06728426,  0.03304253,  0.13753785,
       -0.1500637 , -0.14291327,  0.04301652, -0.11611629,  0.06157324,
       -0.07234827,  0.14717148,  0.2545214 ,  0.0585395 ,  0.03058151,
       -0.21067876,  0.08601779,  0.31477028, -0.2819541 , -0.126506  ,
       -0.08648231,  0.0501729 , -0.13921839,  0.2780563 , -0.15873636,
        0.09821067,  0.08581246,  0.15982471, -0.11639095, -0.01038365,
       -0.03607295, -0.00758556,  0.20937528,  0.1522774 ,  0.04540678,
        0.16202143,  0.300245  ,  0.24711101,  0.13813621,  0.07371245],
      dtype=float32)

In [52]:
model.wv['しない']

array([ 1.83836356e-01, -5.03518768e-02,  3.48990828e-01, -7.04023913e-02,
        6.20005012e-05,  2.78066337e-01, -2.19644621e-01, -2.90431473e-02,
       -1.03101477e-01,  7.16391802e-02,  2.07951948e-01, -1.19780496e-01,
       -1.87755406e-01, -1.33815438e-01,  2.23041937e-01,  9.83613357e-02,
       -6.83583394e-02, -9.06314403e-02, -4.32243682e-02,  2.59494990e-01,
        3.08152521e-03,  1.66904569e-01,  1.00808412e-01, -8.07310715e-02,
        2.00783670e-01, -1.66324794e-01,  5.73687814e-02, -2.40009636e-01,
        1.61649473e-02, -4.73212861e-02,  2.14040086e-01, -3.93376723e-02,
        5.61293960e-02,  1.82965249e-01, -2.89997105e-02, -1.69671718e-02,
        5.86439110e-02,  2.23324731e-01,  2.42065027e-01, -3.18750460e-03,
       -1.37717634e-01,  3.76607589e-02, -6.61148131e-03, -6.74153119e-02,
        1.18622243e-01, -1.15296952e-01,  1.17420308e-01,  3.61279733e-02,
        2.50389054e-02,  3.83239388e-02], dtype=float32)

In [53]:
model.wv['と']

array([ 0.24805464,  0.0942286 , -0.20791826, -0.00756954,  0.06851177,
       -0.31301022,  0.04826369, -0.16889285, -0.21213712, -0.07802629,
        0.08609236,  0.107904  , -0.07175639,  0.01399859, -0.09023309,
        0.0320005 ,  0.10394653,  0.09994207,  0.01535257, -0.06654159,
       -0.02427759,  0.0688901 , -0.13873203, -0.05250924, -0.07093938,
       -0.29809234,  0.05224411,  0.12307699, -0.08560754, -0.11757777,
       -0.1254678 , -0.01158067,  0.31013525, -0.13512704, -0.1734812 ,
        0.13401446,  0.11359649,  0.15362926, -0.17381811,  0.12603985,
       -0.01989314, -0.01380667,  0.13246632, -0.18157282,  0.15528533,
       -0.10789854, -0.23871091,  0.27634004, -0.01682221, -0.0306127 ],
      dtype=float32)

In [54]:
model.wv['ね']

array([ 0.1104566 , -0.33514565, -0.01023961,  0.04472661, -0.1253212 ,
        0.21698283, -0.0644436 , -0.15218998, -0.00115856, -0.16217883,
       -0.12278508,  0.02112044,  0.11264547, -0.2150383 ,  0.231267  ,
        0.03306101, -0.01468965,  0.01849632,  0.07986051,  0.01675842,
        0.17569771,  0.04994076,  0.08301574,  0.20287828, -0.16053656,
       -0.0222069 ,  0.2389448 ,  0.24399199,  0.2683765 ,  0.06304192,
        0.272477  ,  0.09917954,  0.07573809,  0.10092346, -0.13820833,
        0.0945723 , -0.1197267 ,  0.0769465 ,  0.0616007 , -0.26752144,
        0.08279745,  0.0505061 ,  0.05766397, -0.1271001 , -0.00712314,
        0.11122245,  0.00847838,  0.12569211,  0.04569462, -0.19360265],
      dtype=float32)

In [55]:
import numpy as np

In [56]:
c=[0,1]

In [57]:
d=[1,8]

In [58]:
np.dot(c,d)

8

from gensim.models import Word2Vec
bulid english model. and transfer the japanese word to english . 

find the similarity from the english word vector.


In [59]:
model_path = 'data/word2vec/jv.bin'
model = Word2Vec.load(model_path)

In [60]:
print(model)

Word2Vec(vocab=10019, size=100, alpha=0.025)


In [61]:
model_path = 'data/word2vec/ja.bin'
model = Word2Vec.load(model_path)

In [62]:
print(model)

Word2Vec(vocab=50108, size=300, alpha=0.025)


In [63]:
model.wv['ね']

array([ 1.32877374e+00,  3.02616692e+00, -5.73622994e-02,  3.53791773e-01,
        2.34457183e+00, -1.13951421e+00,  1.19330153e-01, -1.64491248e+00,
        1.11891747e+00,  4.73539203e-01, -4.85597342e-01,  2.84659982e+00,
        2.60731649e+00, -9.85718012e-01, -2.22600317e+00,  1.49573177e-01,
       -8.29707921e-01,  2.27776263e-02,  2.08539963e+00,  1.91438782e+00,
       -2.99255461e-01,  8.80297601e-01, -9.25932467e-01,  1.25160086e+00,
        2.49913740e+00,  5.23523152e-01, -1.09095001e+00, -9.14230421e-02,
       -2.81909561e+00,  1.64603508e+00, -8.06828499e-01,  2.21067953e+00,
       -9.80944574e-01,  1.35029483e+00,  5.84483445e-01,  1.43120849e+00,
        4.97377247e-01, -2.86928773e-01,  2.24539614e+00, -4.69064444e-01,
        6.50603652e-01, -2.59231359e-01,  9.59429324e-01, -1.17807031e+00,
        3.41699839e-01, -6.55052960e-01, -1.74239707e+00,  2.02651724e-01,
       -1.15365052e+00, -1.16642010e+00,  7.58471787e-01, -5.31132460e-01,
        5.02245247e-01,  

In [64]:
from gensim.models import FastText

In [65]:
from gensim.models.wrappers.fasttext import FastText
model = FastText.load_fasttext_format('data/fasttext/jv.bin')

FileNotFoundError: [Errno 2] No such file or directory: 'data/fasttext/jv.bin'

In [66]:
print(model)

Word2Vec(vocab=50108, size=300, alpha=0.025)


In [67]:
import os

In [68]:
os.chdir("data/word2vec/")

In [69]:
pwd

'/home/yanhua/Documents/jupyter/yan/demo/RNN/Natural_Language_Processing/data/word2vec'

In [70]:
model = KeyedVectors.load('jv.tsv')
max_vocab = 30000
vocab = list(model.wv.vocab.keys())[:max_vocab]
vectors = [model.wv[word] for word in vocab]

NameError: name 'KeyedVectors' is not defined

![Illustration of the problem](natural_language_flowchart.png)

従来に処理できない情報、データは処理できるようになりました。
#### これから更なる情報処理の時代が始まります。

##### Processing Signal to Other signal 

![Illustration of the problem](machine_translation_flowchart.png)

##### image to signal or signal to image etc...

![Illustration of the problem](image_captioning_flowchart.png)